### PR TITLE
Enhance test to verify that the innermost mono returned by client actually runs

### LINKED ISSUE #49: Update SpannerConnectionTest to fail if implementation flatMap() are replaced by map()
https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/41#pullrequestreview-237291024

Or prove it should not fail.

map() leads to double wrapped Mono. The current test blocks on the outer Mono, so it might verify despite results not yet being available.

### PR DESCRIPTION
**Pull request by elefeint**
Fixes #49.

### CODE REVIEW

File: src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java [hunk 1]
```diff
@@ -116,5 +140,22 @@ public void rollbackTransactions() {
...
+    return Mono.fromSupplier(() -> {
+      counter.addAndGet(1);
+      return returnObjectSupplier.get();
+    });
+  }
+
+  private void verifyTrackingMono(String description, AtomicInteger counter) {
+    assertThat(counter.get())
+        .withFailMessage(description + " publisher was never subscribed to.")
+        .isEqualTo(1);
```
Comment (dzou) [inline src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java]: I think this method could be more clear if the expected count was passed in via parameter; I would also rename the method to maybe `verifyCount` or something similar since it does not accept a mono as a parameter but atomic int instead.

Alternatively, I would also be open to just unrolling the helper function and adding the two assert statements inline since it is only repeated twice.

Comment (elefeint) [reply src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java]: yeah, I think I'll do the latter -- fold the assertions into each test.

File: src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java [hunk 2]
```diff
@@ -92,6 +94,15 @@ public void executeStatementReturnsWorkingStatementWithCorrectQuery() {
...
+    AtomicInteger beginTransactionCounter = new AtomicInteger(0);
+    AtomicInteger commitTransactionCounter = new AtomicInteger(0);
+    when(this.mockClient.beginTransaction(TEST_SESSION))
+        .thenReturn(this.getTrackingMono(
+            () -> Transaction.getDefaultInstance(), beginTransactionCounter));
+    when(this.mockClient.commitTransaction(TEST_SESSION,  Transaction.getDefaultInstance()))
+        .thenReturn(this.getTrackingMono(
+            () -> CommitResponse.getDefaultInstance(), commitTransactionCounter));
+
     Mono.from(connection.commitTransaction()).block();
```
Comment (meltsufin) [inline src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java]: Please add a comment saying what this block is testing... "no-op commit when connection is not started".

File: src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java [hunk 3]
```diff
@@ -101,12 +112,29 @@ public void beginAndCommitTransactions() {
         .beginTransaction(TEST_SESSION);
     verify(this.mockClient, times(1))
         .commitTransaction(TEST_SESSION, Transaction.getDefaultInstance());
+
+    assertThat(beginTransactionCounter.get())
+        .withFailMessage("beginTransaction publisher was never subscribed to.")
+        .isEqualTo(1);
```
Comment (meltsufin) [inline src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java]: I think it reads more fluently if you put `isEqualTo` before `withFailMessage`.

**Comment by elefeint** [comment]
Yes, I have -- there is a tracking issue for it, #55.

PublisherProbe can be useful, although it won't reduce boilerplate that much.

**Comment by meltsufin** [comment]
@elefeint Do you want to try using the `reactor-testing` methods as part of this PR, or leave it for later?

File: src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java (hunk 2 above)
Comment (elefeint) [reply src/test/java/com/google/cloud/spanner/r2dbc/SpannerConnectionTest.java]: I'll just split it off into a small test for only that scenario, since a noop commit does not require any of the other verification in this test.
