### PR TITLE
TCK tests and fixes

### LINKED ISSUE #12: Bring in R2DBC SPI TCK
https://github.com/r2dbc/r2dbc-spi/tree/master/r2dbc-spi-test

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
fixes #12 
makes some fixes as necessary

### CODE REVIEW

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java [hunk 1]
```diff
@@ -88,7 +89,7 @@ public SpannerConnection(Client client, Session session) {
 
   @Override
   public Publisher<Void> close() {
-    return this.client.deleteSession(this.session);
+    return commitTransaction().concatWith(this.client.deleteSession(this.session));
```
Comment (meltsufin) [inline src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java]: What if there is no active transaction? This will cause a warning to be emitted.

Comment (dzou) [inline src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java]: I think using `.then` instead of `.concatWith` would be more accurate since `then` returns a Mono indicating completion; however concatWith returns a flux.

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java [hunk 2]
```diff
@@ -98,16 +97,28 @@ public Statement add() {
 
   @Override
   public Statement bind(Object identifier, Object value) {
-    requireNonNull(identifier);
+    Assert.requireNonNull(identifier, "Identifier must not be null.");
```
Comment (dzou) [inline src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: Add another `Assert.requireNonNull(value)` here because value can no longer be null now right? It must be TypedNull?

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java [hunk 3]
```diff
@@ -98,16 +97,28 @@ public Statement add() {
...
+        valToStore = null;
+        classToStore = ((TypedNull) value).getType();
+      } else {
+        valToStore = value;
+        classToStore = value.getClass();
+      }
+
       Codec codec = this.resolvedCodecs
-          .computeIfAbsent(paramName, n -> this.codecs.getCodec(value));
+          .computeIfAbsent(paramName, n -> this.codecs.getCodec(classToStore));
```
Comment (dzou) [inline src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: Should it be `this.codecos.getCodec(**valToStore**)` instead? I thought `this.codecs.getCodec` accepted the object value and not a Class.

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java [hunk 4]
```diff
@@ -124,7 +135,7 @@ public Statement bind(int i, Object o) {
 
   @Override
   public Statement bindNull(Object identifier, Class<?> type) {
-    return bind(identifier, null);
+    return bind(identifier, new TypedNull(type));
```
Comment (dzou) [inline src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: You can just make this a singleton `private static final` instance to save yourself reinstantiating this.

Comment (meltsufin) [inline src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: In H2, they use `this.codecs.encodeNull(type)`. Can we do the same instead of creating this dummy `TypedNull` class?
@dmitry-s

File: src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java [hunk 5]
```diff
@@ -33,7 +34,7 @@
  */
 public final class DefaultCodecs implements Codecs {
 
-  private static final com.google.protobuf.Value NULL_VALUE =
+  public static final com.google.protobuf.Value NULL_VALUE =
```
Comment (dzou) [inline src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java]: Make this package-private?

File: src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codecs.java [hunk 6]
```diff
@@ -47,6 +47,6 @@
    */
   Value encode(Object value);
 
-  Codec getCodec(Object value);
```
Comment (meltsufin) [inline src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codecs.java]: This would  be a departure from other R2DBC implementations that all operate on the value rather than the type.

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java (hunk 3 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: This can't work because you need the codec of the right type even if the value is null.

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java (hunk 4 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: What do you mean??

Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: I think that's arguably a WORSE way of doing it because the null must be bound to the statement with a type, which is why the individual codec must be found.

File: src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codecs.java (hunk 6 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codecs.java]: This cannot work. A null must come with a type. Furthermore this is our interface and this is a big difference in Spanner vs old-fashioned sql servers that they've exclusively targeted so far.

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java (hunk 4 above)
Comment (dzou) [reply src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: My bad, I thought u could just create a static instance of TypedNull and reuse that; however i forgot you had to pass the type into the constructor.

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java (hunk 1 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java]: will fix

File: src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java (hunk 5 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java]: done

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java (hunk 2 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: done

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java (hunk 1 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/SpannerConnection.java]: Fixed, I made it so that close() will not cause the warning to be logged.

I made close() do commit() because from the TCK tests it appears that using close() to commit a transaction (with no explicit call to commitTransaction) is an acceptable way to commit DML statements.

File: src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codecs.java (hunk 6 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/codecs/Codecs.java]: https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/101

File: src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java (hunk 4 above)
Comment (ChengyuanZhao) [reply src/main/java/com/google/cloud/spanner/r2dbc/SpannerStatement.java]: https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/101

**Comment by ChengyuanZhao** [comment]
I'm gonna be moving on to the large integration tests issue next, so I will be submitting this in 15 minutes if no objections before then.

**Comment by dzou** [comment]
> I'm gonna be moving on to the large integration tests issue next, so I will be submitting this in 15 minutes if no objections before then.

SGTM
