### PR TITLE
Propagate Specific R2dbc Exceptions by Error Code

### LINKED ISSUE #154: Propagate Error Status Code through Exceptions
Currently, we are using `R2dbcTransientException` and `R2dbcNontransientException` to propagate exceptions to the user.

These exceptions do not contain error codes. So we would like to extend a new exception type which specifies transience but also propagate error codes to the user.

context: https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/151#discussion_r298242609

### PR DESCRIPTION
**Pull request by dzou**
If a Spanner-specific exception is thrown, this adds support to extract the error code if present and construct the appropriate R2dbc exception subclass based upon the error code.

Fixes #154.

### CODE REVIEW

File: src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java [hunk 1]
```diff
@@ -238,9 +240,11 @@ public GrpcClient(GoogleCredentials credentials) {
     .flatMapMany(response -> {
       Flux<ResultSet> results = Flux.fromIterable(response.getResultSetsList());
       if (response.hasStatus() && response.getStatus().getCode() != Status.Code.OK.value()) {
-        results = results.concatWith(
-            Mono.error(
-                new R2dbcNonTransientResourceException(response.getStatus().getMessage())));
+        R2dbcException exception =
```
Comment (meltsufin) [inline src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java]: You don't really need this local variable, but if you added it for readability, that's fine.

File: src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java [hunk 2]
```diff
@@ -32,37 +39,81 @@
...
           "Received unexpected EOS on DATA frame from server");
 
+  /**
+   * Manually creates an {@link R2dbcException} from a provided error code and message.
+   *
+   * @param errorCode the Spanner error code of the error.
+   * @param message the error message.
+   * @return the resulting {@link R2dbcException} that is propagated to the user.
+   */
+  public static R2dbcException createR2dbcException(int errorCode, String message) {
```
Comment (meltsufin) [inline src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java]: Seeing how you added a bunch of these `create` methods, would it make sense to just put this logic into `R2dbcExcpetion` constructors instead?
In fact, refactoring this whole class into `R2dbcException` could be an option.

File: src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java (hunk 1 above)
Comment (dzou) [reply src/main/java/com/google/cloud/spanner/r2dbc/client/GrpcClient.java]: Yup, I just had it for readability.

File: src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java (hunk 2 above)
Comment (dzou) [reply src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java]: Ah, I don't think I can quite do that since the R2dbcException classes are owned by the SPI; not controlled by us.

File: src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java [hunk 3]
```diff
@@ -32,37 +39,81 @@
...
+  }
+
+  /**
+   * Extracts metadata of a thrown exception and creates a {@link R2dbcException} from it.
+   *
+   * @param baseException the base exception that is thrown
+   * @return the resulting {@link R2dbcException} that is propagated to the user.
+   */
+  public static R2dbcException createR2dbcException(Throwable baseException) {
+    if (!(baseException instanceof StatusRuntimeException)) {
```
Comment (elefeint) [inline src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java]: I'd check for null `baseException`, just in case.

Comment (dzou) [reply src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java]: Done.

File: src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java (hunk 2 above)
Comment (meltsufin) [reply src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java]: Subclass it?
`SpannerR2dbcException`?

Comment (dzou) [reply src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java]: But I still have to return the correct subclass of R2dbcException such as: R2dbcDataIntegrityViolationException, R2dbcBadGrammarException, etc. These extend R2dbcException.

Comment (meltsufin) [reply src/main/java/com/google/cloud/spanner/r2dbc/util/SpannerExceptionUtil.java]: Ah, good point. That would be annoying to subclass all of them.
