### PR TITLE
Test metadata column name fix

### LINKED ISSUE #70: asserts are not working
I moved these asserts and the tests are failing.

```java
assertThat(columnMetadata).isEqualTo(results.get(0).getRowMetadata().getColumnMetadatas());
    assertThat(columnMetadata).isEqualTo(results.get(1).getRowMetadata().getColumnMetadatas());
```

https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/c84f0305777253f855865145aee3ecc3a8db0d18/src/test/java/com/google/cloud/spanner/r2dbc/result/PartialResultRowExtractorTest.java#L199-L202

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
fixes #70 
tests metadata colum names properly.

### CODE REVIEW

File: src/test/java/com/google/cloud/spanner/r2dbc/result/PartialResultRowExtractorTest.java [hunk 1]
```diff
@@ -196,10 +197,19 @@ private void verifyRows(Flux<PartialResultSet> inputs) {
         .map(SpannerColumnMetadata::new)
         .collect(Collectors.toList());
 
-    assertThat(
-        Objects.areEqual(columnMetadata, results.get(0).getRowMetadata().getColumnMetadatas()));
-    assertThat(
-        Objects.areEqual(columnMetadata, results.get(1).getRowMetadata().getColumnMetadatas()));
+    assertThat(Objects
```
Comment (dzou) [inline src/test/java/com/google/cloud/spanner/r2dbc/result/PartialResultRowExtractorTest.java]: Since the compared variables are long, can you break it up into multiple lines to assist readability?

i.e.:

```
expectedMetadata = X;
actualMetadata = Y;
assertThat(actual).isEqualTo(expected);
```

Also I think it would be more clear to use `assertThat(...).isEqualTo(..)` instead of `assertThat(Objects.areEqual(..)).isTrue()`

Comment (ChengyuanZhao) [reply src/test/java/com/google/cloud/spanner/r2dbc/result/PartialResultRowExtractorTest.java]: done ptal
